default_platform(:android)

platform :android do
  desc "Run all tests and deploy to jcenter"
  lane :deploy do
    gradle(
        task: "test ktlintFormat clean build install bintrayUpload"
    )
  end
end
