import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val annotation: String = "androidx.annotation:annotation:" + Versions.annotation

  /**
   * https://developer.android.com/jetpack/androidx
   */
  const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

  /**
   * http://tools.android.com
   */
  const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
      Versions.constraintlayout

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val lifecycle_extensions: String = "androidx.lifecycle:lifecycle-extensions:" +
      Versions.androidx_lifecycle

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val lifecycle_reactivestreams_ktx: String =
      "androidx.lifecycle:lifecycle-reactivestreams-ktx:" + Versions.androidx_lifecycle

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val recyclerview: String = "androidx.recyclerview:recyclerview:" + Versions.recyclerview

  /**
   * https://developer.android.com/studio
   */
  const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

  /**
   * https://developer.android.com/studio
   */
  const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
      Versions.com_android_tools_build_gradle

  /**
   * https://developer.android.com/studio
   */
  const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

  /**
   * https://github.com/dcendents/android-maven-gradle-plugin
   */
  const val android_maven_gradle_plugin: String =
      "com.github.dcendents:android-maven-gradle-plugin:" + Versions.android_maven_gradle_plugin

  /**
   * https://github.com/google/gson
   */
  const val gson: String = "com.google.code.gson:gson:" + Versions.gson

  /**
   * https://github.com/JakeWharton/RxBinding/
   */
  const val rxbinding_appcompat: String = "com.jakewharton.rxbinding3:rxbinding-appcompat:" +
      Versions.com_jakewharton_rxbinding3

  /**
   * https://github.com/JakeWharton/RxBinding/
   */
  const val rxbinding_recyclerview: String = "com.jakewharton.rxbinding3:rxbinding-recyclerview:" +
      Versions.com_jakewharton_rxbinding3

  /**
   * https://github.com/JakeWharton/RxBinding/
   */
  const val rxbinding: String = "com.jakewharton.rxbinding3:rxbinding:" +
      Versions.com_jakewharton_rxbinding3

  /**
   * https://github.com/JakeWharton/timber
   */
  const val timber: String = "com.jakewharton.timber:timber:" + Versions.timber

  const val gradle_bintray_plugin: String = "com.jfrog.bintray.gradle:gradle-bintray-plugin:" +
      Versions.gradle_bintray_plugin

  /**
   * https://github.com/pinterest/ktlint
   */
  const val ktlint: String = "com.pinterest:ktlint:" + Versions.ktlint

  /**
   * https://github.com/square/retrofit/
   */
  const val adapter_rxjava2: String = "com.squareup.retrofit2:adapter-rxjava2:" +
      Versions.com_squareup_retrofit2

  /**
   * https://github.com/square/retrofit/
   */
  const val converter_gson: String = "com.squareup.retrofit2:converter-gson:" +
      Versions.com_squareup_retrofit2

  /**
   * https://github.com/square/retrofit/
   */
  const val retrofit: String = "com.squareup.retrofit2:retrofit:" + Versions.com_squareup_retrofit2

  const val buildsrcversions: String = "de.fayard:buildSrcVersions:" + Versions.buildsrcversions

  /**
   * https://github.com/ReactiveX/RxAndroid
   */
  const val rxandroid: String = "io.reactivex.rxjava2:rxandroid:" + Versions.rxandroid

  /**
   * https://github.com/ReactiveX/RxJava
   */
  const val rxjava: String = "io.reactivex.rxjava2:rxjava:" + Versions.rxjava

  /**
   * http://junit.org
   */
  const val junit: String = "junit:junit:" + Versions.junit

  const val dokka_android_gradle_plugin: String =
      "org.jetbrains.dokka:dokka-android-gradle-plugin:" + Versions.dokka_android_gradle_plugin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions_runtime: String =
      "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions: String = "org.jetbrains.kotlin:kotlin-android-extensions:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_stdlib_jdk7: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" +
      Versions.org_jetbrains_kotlin

  const val koin_android: String = "org.koin:koin-android:" + Versions.org_koin

  const val koin_androidx_viewmodel: String = "org.koin:koin-androidx-viewmodel:" +
      Versions.org_koin

  const val koin_core: String = "org.koin:koin-core:" + Versions.org_koin

  const val koin_test: String = "org.koin:koin-test:" + Versions.org_koin
}
